"""Spark translation of the shared feature specification.

**No feature is defined here.** Every column is generated by iterating over
``telemetry_core.features.FEATURE_SPECS`` and ``CORRELATION_PAIRS``, so adding a
feature in a later phase requires no change to this module and cannot produce a
silently different definition on the streaming side.

The semantics that engines disagree on, and how they are preserved:

* ``stddev_samp`` -- ddof=1, matching the reference and pandas. Spark's
  ``stddev`` aliases ``stddev_samp``, but the explicit name is used so nobody has
  to check.
* "first" and "last" mean ``min_by(value, masked_time)`` and
  ``max_by(value, masked_time)``, **never** ``first()``/``last()``, which are
  non-deterministic after a shuffle. The timestamp is masked to null wherever
  the signal is null, so these mean "first and last *reported* sample". A probe
  confirmed Spark ignores rows whose ordering column is null: on values
  ``[10, null, 30, null]`` at 0/10/20/30 s it returns first=10, last=30,
  elapsed=20 s, exactly as the reference does.
* ``corr`` performs pairwise deletion natively and returns **null** -- not zero,
  not NaN -- when a signal has no variance. A frozen sensor lands there, and the
  null is the detection signal. Confirmed by probe.
* Ratios are computed per sample, before aggregation. The mean of a ratio is not
  the ratio of the means.
"""

from __future__ import annotations

from pyspark.sql import Column, DataFrame
from pyspark.sql import functions as F
from telemetry_core.features import (
    CORRELATION_PAIRS,
    DERIVED_SIGNALS,
    FEATURE_NAMES,
    FEATURE_SPECS,
    AggregationKind,
)
from telemetry_core.schemas import SENSOR_NAMES

from stream_processor.source import epoch_millis

__all__ = [
    "ALL_SIGNALS",
    "MIN_ROTATION_RPM",
    "RUNNING_STATE",
    "aggregate_windows",
    "derive_features",
    "prepare_signals",
    "window_aggregations",
]

ALL_SIGNALS: tuple[str, ...] = (*SENSOR_NAMES, *DERIVED_SIGNALS)
RUNNING_STATE = "RUNNING"

#: Below one revolution per minute the ratio is meaningless: dividing by a
#: near-stopped motor manufactures an enormous value that a model reads as a
#: dramatic anomaly, when the machine is merely idle.
MIN_ROTATION_RPM = 1.0


def prepare_signals(frame: DataFrame) -> DataFrame:
    """Add the per-sample derived ratios, masked timestamps and quality flags."""
    turning = F.col("rotation_rpm").isNotNull() & (F.col("rotation_rpm") >= MIN_ROTATION_RPM)

    prepared = frame.withColumn(
        "power_per_rpm",
        F.when(turning & F.col("power_kw").isNotNull(), F.col("power_kw") / F.col("rotation_rpm")),
    ).withColumn(
        "vibration_per_rpm",
        F.when(
            turning & F.col("vibration_mm_s").isNotNull(),
            F.col("vibration_mm_s") / F.col("rotation_rpm"),
        ),
    )

    event_millis = epoch_millis(F.col("event_time"))
    for signal in ALL_SIGNALS:
        # The masked timestamp is what makes min_by/max_by mean "first and last
        # sample that actually reported this signal".
        prepared = prepared.withColumn(
            f"__t_{signal}", F.when(F.col(signal).isNotNull(), event_millis)
        )

    null_count: Column = sum(  # type: ignore[assignment]
        F.col(name).isNull().cast("int") for name in SENSOR_NAMES
    )
    return prepared.withColumn("__null_count", null_count).withColumn(
        "__running", (F.col("machine_state") == F.lit(RUNNING_STATE)).cast("double")
    )


def window_aggregations() -> list[Column]:
    """Every aggregate the specification needs, in one pass."""
    aggregations: list[Column] = []
    for signal in ALL_SIGNALS:
        masked_time = F.col(f"__t_{signal}")
        aggregations.extend(
            [
                F.avg(signal).alias(f"{signal}__mean"),
                F.stddev_samp(signal).alias(f"{signal}__stddev"),
                F.min(signal).alias(f"{signal}__min"),
                F.max(signal).alias(f"{signal}__max"),
                F.min_by(signal, masked_time).alias(f"{signal}__first"),
                F.max_by(signal, masked_time).alias(f"{signal}__last"),
                F.min(masked_time).alias(f"{signal}__t_first"),
                F.max(masked_time).alias(f"{signal}__t_last"),
            ]
        )

    for pair in CORRELATION_PAIRS:
        aggregations.append(F.corr(pair.left, pair.right).alias(pair.name))

    aggregations.extend(
        [
            F.count(F.lit(1)).alias("__sample_count"),
            F.sum("__null_count").alias("__null_total"),
            F.avg("__running").alias("running_ratio"),
            # Deterministic "last state" and "the line this machine belongs to".
            F.max_by("machine_state", F.col("event_time")).alias("machine_state"),
            F.max_by("line_id", F.col("event_time")).alias("line_id"),
        ]
    )
    return aggregations


def aggregate_windows(
    prepared: DataFrame, *, window_duration: str, slide_duration: str, watermark_delay: str
) -> DataFrame:
    """Windowed aggregation on event time, keyed by machine."""
    return (
        prepared.withWatermark("event_time", watermark_delay)
        .groupBy(
            F.window(F.col("event_time"), window_duration, slide_duration).alias("window"),
            F.col("machine_id"),
        )
        .agg(*window_aggregations())
    )


def _feature_column(signal: str, kind: AggregationKind) -> Column:
    mean = F.col(f"{signal}__mean")
    stddev = F.col(f"{signal}__stddev")
    first = F.col(f"{signal}__first")
    last = F.col(f"{signal}__last")
    elapsed_seconds = (F.col(f"{signal}__t_last") - F.col(f"{signal}__t_first")) / F.lit(1000.0)

    if kind is AggregationKind.MEAN:
        return mean
    if kind is AggregationKind.STDDEV:
        return stddev
    if kind is AggregationKind.MIN:
        return F.col(f"{signal}__min")
    if kind is AggregationKind.MAX:
        return F.col(f"{signal}__max")
    if kind is AggregationKind.RANGE:
        return F.col(f"{signal}__max") - F.col(f"{signal}__min")
    if kind is AggregationKind.SLOPE:
        return F.when(elapsed_seconds > F.lit(0.0), (last - first) / elapsed_seconds)
    if kind is AggregationKind.DEVIATION_FROM_MEAN:
        return last - mean
    if kind is AggregationKind.ZSCORE_LAST:
        # Undefined, not zero: a flat signal has no scale to measure against.
        return F.when(stddev > F.lit(0.0), (last - mean) / stddev)
    raise ValueError(f"unhandled aggregation: {kind}")  # pragma: no cover


def derive_features(aggregated: DataFrame) -> DataFrame:
    """Turn the raw aggregates into the 52 named features, in canonical order."""
    sample_count = F.col("__sample_count").cast("double")
    columns: list[Column] = [
        F.col("machine_id"),
        F.col("window.start").alias("window_start"),
        F.col("window.end").alias("window_end"),
        F.col("running_ratio"),
        F.col("machine_state"),
        F.col("line_id"),
    ]

    for spec in FEATURE_SPECS:
        columns.append(_feature_column(spec.signal, spec.aggregation).alias(spec.name))
    for pair in CORRELATION_PAIRS:
        columns.append(F.col(pair.name))
    columns.append(sample_count.alias("sample_count"))
    columns.append(
        F.when(
            sample_count > F.lit(0.0),
            F.col("__null_total").cast("double") / (sample_count * F.lit(len(SENSOR_NAMES))),
        ).alias("null_ratio")
    )

    derived = aggregated.select(*columns)
    missing = [name for name in FEATURE_NAMES if name not in derived.columns]
    if missing:  # pragma: no cover - guards a specification/translation drift
        raise RuntimeError(f"feature translation is missing columns: {missing}")
    return derived
